version: '3.1'

services:
  vending-machine:
    image: vending-machine
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: compose
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shq
    ports:
      - 3306:3306
    logging:
      driver: none