spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/shq
    username: root
  flyway:
    enabled: true
    password: password
    url: jdbc:mysql://localhost:3306/shq
    user: root
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  main:
    banner-mode: off
logging:
  level:
    root: OFF